package com.liferay.devhacks.model.impl;

import com.liferay.devhacks.model.Note;

/**
 * The extended model base implementation for the Note service. Represents a row in the &quot;Templates_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NoteImpl}.
 * </p>
 *
 * @author James Falkner
 * @see NoteImpl
 * @see com.liferay.devhacks.model.Note
 * @generated
 */
public abstract class NoteBaseImpl extends NoteModelImpl implements Note {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a note model instance should use the {@link Note} interface instead.
     */
}
