package com.liferay.devhacks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Note service. Represents a row in the &quot;Templates_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.devhacks.model.impl.NoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.devhacks.model.impl.NoteImpl}.
 * </p>
 *
 * @author James Falkner
 * @see Note
 * @see com.liferay.devhacks.model.impl.NoteImpl
 * @see com.liferay.devhacks.model.impl.NoteModelImpl
 * @generated
 */
public interface NoteModel extends BaseModel<Note> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a note model instance should use the {@link Note} interface instead.
     */

    /**
     * Returns the primary key of this note.
     *
     * @return the primary key of this note
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this note.
     *
     * @param primaryKey the primary key of this note
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the name of this note.
     *
     * @return the name of this note
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this note.
     *
     * @param name the name of this note
     */
    public void setName(String name);

    /**
     * Returns the note of this note.
     *
     * @return the note of this note
     */
    @AutoEscape
    public String getNote();

    /**
     * Sets the note of this note.
     *
     * @param note the note of this note
     */
    public void setNote(String note);

    /**
     * Returns the note ID of this note.
     *
     * @return the note ID of this note
     */
    public long getNoteId();

    /**
     * Sets the note ID of this note.
     *
     * @param noteId the note ID of this note
     */
    public void setNoteId(long noteId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.devhacks.model.Note note);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.devhacks.model.Note> toCacheModel();

    @Override
    public com.liferay.devhacks.model.Note toEscapedModel();

    @Override
    public com.liferay.devhacks.model.Note toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
